image: node:latest

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  variables:
    DEPLOY_URL: "https://shujinarazaki.gitlab.io"
  script:
    - npm rebuild node-sass
    - npm run update
    - npm run generate
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
