image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

variable:
  DEPLOY_URL: "https://shujinarazaki.gitlab.io"

pages:
  script:
    - npm run update
    - npm run generate
  artifacts:
    paths:
      - public
  only:
    - master
