name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prepare and Generate
      run: npm install & npm run generate
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        FOLDER: build
